//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spike.Providers.WCF.Proxy.IdentityResolverService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="Spike.Providers", ConfigurationName="IdentityResolverService.IdentityResolverService")]
    public interface IdentityResolverService {
        
        [System.ServiceModel.OperationContractAttribute(Action="Spike.Providers/IdentityResolverService/RegisterUser", ReplyAction="Spike.Providers/IdentityResolverService/RegisterUserResponse")]
        Spike.Contracts.Security.CommonIdentity RegisterUser(Spike.Contracts.Security.CommonIdentity user);
        
        [System.ServiceModel.OperationContractAttribute(Action="Spike.Providers/IdentityResolverService/RegisterUser", ReplyAction="Spike.Providers/IdentityResolverService/RegisterUserResponse")]
        System.Threading.Tasks.Task<Spike.Contracts.Security.CommonIdentity> RegisterUserAsync(Spike.Contracts.Security.CommonIdentity user);
        
        [System.ServiceModel.OperationContractAttribute(Action="Spike.Providers/IdentityResolverService/DeleteUser", ReplyAction="Spike.Providers/IdentityResolverService/DeleteUserResponse")]
        Spike.Contracts.Security.CommonIdentity DeleteUser(string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="Spike.Providers/IdentityResolverService/DeleteUser", ReplyAction="Spike.Providers/IdentityResolverService/DeleteUserResponse")]
        System.Threading.Tasks.Task<Spike.Contracts.Security.CommonIdentity> DeleteUserAsync(string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="Spike.Providers/IdentityResolverService/GetUser", ReplyAction="Spike.Providers/IdentityResolverService/GetUserResponse")]
        Spike.Contracts.Security.CommonIdentity GetUser(string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="Spike.Providers/IdentityResolverService/GetUser", ReplyAction="Spike.Providers/IdentityResolverService/GetUserResponse")]
        System.Threading.Tasks.Task<Spike.Contracts.Security.CommonIdentity> GetUserAsync(string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="Spike.Providers/IdentityResolverService/GetUserClaims", ReplyAction="Spike.Providers/IdentityResolverService/GetUserClaimsResponse")]
        System.Security.Claims.Claim[] GetUserClaims(string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="Spike.Providers/IdentityResolverService/GetUserClaims", ReplyAction="Spike.Providers/IdentityResolverService/GetUserClaimsResponse")]
        System.Threading.Tasks.Task<System.Security.Claims.Claim[]> GetUserClaimsAsync(string userName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IdentityResolverServiceChannel : Spike.Providers.WCF.Proxy.IdentityResolverService.IdentityResolverService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IdentityResolverServiceClient : System.ServiceModel.ClientBase<Spike.Providers.WCF.Proxy.IdentityResolverService.IdentityResolverService>, Spike.Providers.WCF.Proxy.IdentityResolverService.IdentityResolverService {
        
        public IdentityResolverServiceClient() {
        }
        
        public IdentityResolverServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IdentityResolverServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IdentityResolverServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IdentityResolverServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Spike.Contracts.Security.CommonIdentity RegisterUser(Spike.Contracts.Security.CommonIdentity user) {
            return base.Channel.RegisterUser(user);
        }
        
        public System.Threading.Tasks.Task<Spike.Contracts.Security.CommonIdentity> RegisterUserAsync(Spike.Contracts.Security.CommonIdentity user) {
            return base.Channel.RegisterUserAsync(user);
        }
        
        public Spike.Contracts.Security.CommonIdentity DeleteUser(string userName) {
            return base.Channel.DeleteUser(userName);
        }
        
        public System.Threading.Tasks.Task<Spike.Contracts.Security.CommonIdentity> DeleteUserAsync(string userName) {
            return base.Channel.DeleteUserAsync(userName);
        }
        
        public Spike.Contracts.Security.CommonIdentity GetUser(string userName) {
            return base.Channel.GetUser(userName);
        }
        
        public System.Threading.Tasks.Task<Spike.Contracts.Security.CommonIdentity> GetUserAsync(string userName) {
            return base.Channel.GetUserAsync(userName);
        }
        
        public System.Security.Claims.Claim[] GetUserClaims(string userName) {
            return base.Channel.GetUserClaims(userName);
        }
        
        public System.Threading.Tasks.Task<System.Security.Claims.Claim[]> GetUserClaimsAsync(string userName) {
            return base.Channel.GetUserClaimsAsync(userName);
        }
    }
}
